# Seed
default_seed: 20

# Paths
input_path: "dataset"
output_path: "results"
data_path: "IGCT"
target_folder: "S"
condition_folder: "PA2S"

# Training settings
training: True
generate_sample: False
physics_informed: True
polar_cnn: False
conditioned_prior: True
threshold_training: False
clip_grad: False
ema: False
resolution: 64
validation_split: 0.2
test_split: 0.2
loss: "l2"
noise_schedule: "fixed_linear"

# Training parameters
epochs: 500
noise_steps: 250
batch_size: 4
init_lr: 0.00002
weight_decay: 0.001
threshold: 0.01
sample_number: 5
sample_epoch: 50
ema_decay: 0.999

# Test settings
testing: False
calculate_metrics: False
sample_metrics: True
test_path: "results/UNet_bs(4)_noisesteps(250)_loss(l2)_prior(True)_1"
sample_model: "best_model.pth"
nr_samples: 1

# Model Parameters
model_name: "UNet"  
n_blocks: 4
n_channels: 32